FROM node:14.0.0

ENV CHROME_BIN=chromium

WORKDIR /app

RUN echo "deb http://archive.debian.org/debian/ stretch main" > /etc/apt/sources.list \
    && echo "deb-src http://archive.debian.org/debian/ stretch main" >> /etc/apt/sources.list \
    && apt-get update && apt-get install -y chromium


COPY package-lock.json .
COPY package.json .

RUN npm i && npm i -g @angular/cli

COPY . .